version: "3.5"

services:
  db:
    container_name: ${APP_NAME}_prod_db
    restart: always

  web:
    container_name: ${APP_NAME}_prod_web
    restart: always
    ports:
      - 8000:80

  adminer:
    container_name: ${APP_NAME}_prod_adminer
    restart: always
    ports:
      - 8080:8080
