version: "3.5"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

    volumes:
      - ./_docker/data/db:/var/lib/mysql

  web:
    user: $CURRENT_UID
    links:
      - db:mysql
    sysctls:
      net.ipv4.ip_unprivileged_port_start: "0"
    command: 'bash -c "sh /_docker/startup.sh"'
    image: $BUILD_IMAGE
    volumes:
      - ./_docker:/_docker
      - ./_wordpress:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/$APP_NAME
      - ./_docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    depends_on:
      - db
    environment:
      HOME: /_docker/data/home
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE

  adminer:
    image: adminer
