version: "3.5"

services:
  db:
    image: postgres:11-alpine
    volumes:
      - ./_docker/data/db:/var/lib/postgresql/data

  web:
    user: ${CURRENT_UID}
    links:
      - db:mysql
    command: 'bash -c "sh ./_docker/startup.sh"'
    working_dir: /app
    image: $BUILD_IMAGE
    volumes:
      - .:/app
      - ./_docker/data/home:/home/docker
      - /etc/passwd:/etc/passwd
    depends_on:
      - db
    environment:
      - HOME=/app/_docker/data/home
      - BUNDLE_PATH=/app/_docker/data/bundle

  adminer:
    image: adminer
